language: go
go:
- 1.3
- 1.4
- 1.5
- 1.6
- 1.7
- tip
sudo: required
cache:
  apt: true
  directories:
  - $HOME/.gimme
  - $HOME/.frey
env:
  global:
  - GO15VENDOREXPERIMENT=1
  - secure: Ls76vWCzitRPJ4gyIAj7SdAUkbp2hhYd0zsDjHXriZA+KmlrZLsr4L3QcOaX+MMjMyEURZMS43VVaygP6Y8oF5yv4wYBHKgYh0ZW96pWrIS++0B5lo+2U+JZtTKAfLnOLHUQfLL5h4fg9+oa4mlcuH+3FvaCwO0TJjLU1b0q3Fc=
  - secure: aAfgsISNfOC/8FDZSctCJr/JnxxnPkd1o0Zcqc+mTw6NXUa4T3o+aqbaY/VK5lk7Pru9exs5j+HdaeGhQrLMZJca803Sg1r0m68+h/2bS58p9zjyPk7aULCSAF7EUlqT041QQ5UBJV7gpIxFW1nyD6vL0ZBW1wA1k1PpxTjznPA=
matrix:
  allow_failures:
  - go: tip
install:
- export PACKAGES=$(find ./ -maxdepth 2 -name '*.go' -printf '%h\n' | sort | uniq)
- rsync -r ./vendor/ $GOPATH/src
- go get $PACKAGES
script:
- go test $PACKAGES
before_deploy:
- ./.scripts/build_all.sh
deploy:
  provider: releases
  api_key:
    secure: dV3wr9ebEps3YrzIoqmkYc7fw0IECz7QLPRENPSxTJyd5TTYXGsnTS26cMe2LdGwYrXw0njt2GGovMyBZFTtxyYI3mMO4AZRwvZfx/yGzPWJBbVi6NjZVRg/bpyK+mQJ5BUlkPAYJmRpdc6qD+nvCGakBOxoByC5XDK+yM+bKFs=
  file_glob: true
  file: tusd_*.*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    go: 1.7
    repo: tus/tusd
after_deploy:
- make frey && frey setup --force-yes --projectDir .infra
